/*
** DON'T EDIT THIS FILE **
It's been generated by Zapatos, and is liable to be overwritten

Zapatos: https://jawj.github.io/zapatos/
Copyright (C) 2020 - 2023 George MacKerron
Released under the MIT licence: see LICENCE file
*/

declare module 'zapatos/schema' {

  import type * as db from 'zapatos/db';

  // got a type error on schemaVersionCanary below? update by running `npx zapatos`
  export interface schemaVersionCanary extends db.SchemaVersionCanary { version: 104 }


  /* === schema: public === */

  /* --- enums --- */
  /* (none) */

  /* --- tables --- */

  /**
   * **RopewikiImage**
   * - Table in database
   */
  export namespace RopewikiImage {
    export type Table = 'RopewikiImage';
    export interface Selectable {
      /**
      * **RopewikiImage.betaSection**
      * - `uuid` in database
      * - Nullable, no default
      */
      betaSection: string | null;
      /**
      * **RopewikiImage.caption**
      * - `text` in database
      * - Nullable, no default
      */
      caption: string | null;
      /**
      * **RopewikiImage.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt: Date;
      /**
      * **RopewikiImage.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt: Date | null;
      /**
      * **RopewikiImage.fileUrl**
      * - `text` in database
      * - Nullable, no default
      */
      fileUrl: string | null;
      /**
      * **RopewikiImage.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      id: string;
      /**
      * **RopewikiImage.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate: Date;
      /**
      * **RopewikiImage.linkUrl**
      * - `text` in database
      * - Nullable, no default
      */
      linkUrl: string | null;
      /**
      * **RopewikiImage.ropewikiPage**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      ropewikiPage: string;
      /**
      * **RopewikiImage.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt: Date;
    }
    export interface JSONSelectable {
      /**
      * **RopewikiImage.betaSection**
      * - `uuid` in database
      * - Nullable, no default
      */
      betaSection: string | null;
      /**
      * **RopewikiImage.caption**
      * - `text` in database
      * - Nullable, no default
      */
      caption: string | null;
      /**
      * **RopewikiImage.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt: db.TimestampString;
      /**
      * **RopewikiImage.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt: db.TimestampString | null;
      /**
      * **RopewikiImage.fileUrl**
      * - `text` in database
      * - Nullable, no default
      */
      fileUrl: string | null;
      /**
      * **RopewikiImage.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      id: string;
      /**
      * **RopewikiImage.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate: db.TimestampString;
      /**
      * **RopewikiImage.linkUrl**
      * - `text` in database
      * - Nullable, no default
      */
      linkUrl: string | null;
      /**
      * **RopewikiImage.ropewikiPage**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      ropewikiPage: string;
      /**
      * **RopewikiImage.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt: db.TimestampString;
    }
    export interface Whereable {
      /**
      * **RopewikiImage.betaSection**
      * - `uuid` in database
      * - Nullable, no default
      */
      betaSection?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiImage.caption**
      * - `text` in database
      * - Nullable, no default
      */
      caption?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiImage.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiImage.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiImage.fileUrl**
      * - `text` in database
      * - Nullable, no default
      */
      fileUrl?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiImage.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiImage.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiImage.linkUrl**
      * - `text` in database
      * - Nullable, no default
      */
      linkUrl?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiImage.ropewikiPage**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      ropewikiPage?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiImage.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **RopewikiImage.betaSection**
      * - `uuid` in database
      * - Nullable, no default
      */
      betaSection?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiImage.caption**
      * - `text` in database
      * - Nullable, no default
      */
      caption?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiImage.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiImage.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiImage.fileUrl**
      * - `text` in database
      * - Nullable, no default
      */
      fileUrl?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiImage.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiImage.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiImage.linkUrl**
      * - `text` in database
      * - Nullable, no default
      */
      linkUrl?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiImage.ropewikiPage**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      ropewikiPage: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **RopewikiImage.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **RopewikiImage.betaSection**
      * - `uuid` in database
      * - Nullable, no default
      */
      betaSection?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiImage.caption**
      * - `text` in database
      * - Nullable, no default
      */
      caption?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiImage.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiImage.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiImage.fileUrl**
      * - `text` in database
      * - Nullable, no default
      */
      fileUrl?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiImage.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiImage.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiImage.linkUrl**
      * - `text` in database
      * - Nullable, no default
      */
      linkUrl?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiImage.ropewikiPage**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      ropewikiPage?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **RopewikiImage.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'RopewikiImage_pkey' | 'uk_ropewikiImage_ropewikiPage_betaSection_fileUrl';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **RopewikiPage**
   * - Table in database
   */
  export namespace RopewikiPage {
    export type Table = 'RopewikiPage';
    export interface Selectable {
      /**
      * **RopewikiPage.coordinates**
      * - `jsonb` in database
      * - Nullable, no default
      */
      coordinates: db.JSONValue | null;
      /**
      * **RopewikiPage.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt: Date;
      /**
      * **RopewikiPage.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt: Date | null;
      /**
      * **RopewikiPage.hike**
      * - `jsonb` in database
      * - Nullable, no default
      */
      hike: db.JSONValue | null;
      /**
      * **RopewikiPage.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      id: string;
      /**
      * **RopewikiPage.kmlUrl**
      * - `text` in database
      * - Nullable, no default
      */
      kmlUrl: string | null;
      /**
      * **RopewikiPage.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate: Date;
      /**
      * **RopewikiPage.maxTime**
      * - `jsonb` in database
      * - Nullable, no default
      */
      maxTime: db.JSONValue | null;
      /**
      * **RopewikiPage.minTime**
      * - `jsonb` in database
      * - Nullable, no default
      */
      minTime: db.JSONValue | null;
      /**
      * **RopewikiPage.months**
      * - `jsonb` in database
      * - Nullable, no default
      */
      months: db.JSONValue | null;
      /**
      * **RopewikiPage.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name: string;
      /**
      * **RopewikiPage.pageId**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      pageId: string;
      /**
      * **RopewikiPage.permits**
      * - `text` in database
      * - Nullable, no default
      */
      permits: string | null;
      /**
      * **RopewikiPage.quality**
      * - `numeric` in database
      * - Nullable, no default
      */
      quality: db.NumericString | null;
      /**
      * **RopewikiPage.rappelCount**
      * - `text` in database
      * - Nullable, no default
      */
      rappelCount: string | null;
      /**
      * **RopewikiPage.rappelLongest**
      * - `jsonb` in database
      * - Nullable, no default
      */
      rappelLongest: db.JSONValue | null;
      /**
      * **RopewikiPage.rating**
      * - `text` in database
      * - Nullable, no default
      */
      rating: string | null;
      /**
      * **RopewikiPage.region**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      region: string;
      /**
      * **RopewikiPage.riskRating**
      * - `text` in database
      * - Nullable, no default
      */
      riskRating: string | null;
      /**
      * **RopewikiPage.shuttle**
      * - `jsonb` in database
      * - Nullable, no default
      */
      shuttle: db.JSONValue | null;
      /**
      * **RopewikiPage.technicalRating**
      * - `text` in database
      * - Nullable, no default
      */
      technicalRating: string | null;
      /**
      * **RopewikiPage.timeRating**
      * - `text` in database
      * - Nullable, no default
      */
      timeRating: string | null;
      /**
      * **RopewikiPage.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt: Date;
      /**
      * **RopewikiPage.url**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      url: string;
      /**
      * **RopewikiPage.vehicle**
      * - `text` in database
      * - Nullable, no default
      */
      vehicle: string | null;
      /**
      * **RopewikiPage.waterRating**
      * - `text` in database
      * - Nullable, no default
      */
      waterRating: string | null;
    }
    export interface JSONSelectable {
      /**
      * **RopewikiPage.coordinates**
      * - `jsonb` in database
      * - Nullable, no default
      */
      coordinates: db.JSONValue | null;
      /**
      * **RopewikiPage.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt: db.TimestampString;
      /**
      * **RopewikiPage.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt: db.TimestampString | null;
      /**
      * **RopewikiPage.hike**
      * - `jsonb` in database
      * - Nullable, no default
      */
      hike: db.JSONValue | null;
      /**
      * **RopewikiPage.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      id: string;
      /**
      * **RopewikiPage.kmlUrl**
      * - `text` in database
      * - Nullable, no default
      */
      kmlUrl: string | null;
      /**
      * **RopewikiPage.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate: db.TimestampString;
      /**
      * **RopewikiPage.maxTime**
      * - `jsonb` in database
      * - Nullable, no default
      */
      maxTime: db.JSONValue | null;
      /**
      * **RopewikiPage.minTime**
      * - `jsonb` in database
      * - Nullable, no default
      */
      minTime: db.JSONValue | null;
      /**
      * **RopewikiPage.months**
      * - `jsonb` in database
      * - Nullable, no default
      */
      months: db.JSONValue | null;
      /**
      * **RopewikiPage.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name: string;
      /**
      * **RopewikiPage.pageId**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      pageId: string;
      /**
      * **RopewikiPage.permits**
      * - `text` in database
      * - Nullable, no default
      */
      permits: string | null;
      /**
      * **RopewikiPage.quality**
      * - `numeric` in database
      * - Nullable, no default
      */
      quality: number | null;
      /**
      * **RopewikiPage.rappelCount**
      * - `text` in database
      * - Nullable, no default
      */
      rappelCount: string | null;
      /**
      * **RopewikiPage.rappelLongest**
      * - `jsonb` in database
      * - Nullable, no default
      */
      rappelLongest: db.JSONValue | null;
      /**
      * **RopewikiPage.rating**
      * - `text` in database
      * - Nullable, no default
      */
      rating: string | null;
      /**
      * **RopewikiPage.region**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      region: string;
      /**
      * **RopewikiPage.riskRating**
      * - `text` in database
      * - Nullable, no default
      */
      riskRating: string | null;
      /**
      * **RopewikiPage.shuttle**
      * - `jsonb` in database
      * - Nullable, no default
      */
      shuttle: db.JSONValue | null;
      /**
      * **RopewikiPage.technicalRating**
      * - `text` in database
      * - Nullable, no default
      */
      technicalRating: string | null;
      /**
      * **RopewikiPage.timeRating**
      * - `text` in database
      * - Nullable, no default
      */
      timeRating: string | null;
      /**
      * **RopewikiPage.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt: db.TimestampString;
      /**
      * **RopewikiPage.url**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      url: string;
      /**
      * **RopewikiPage.vehicle**
      * - `text` in database
      * - Nullable, no default
      */
      vehicle: string | null;
      /**
      * **RopewikiPage.waterRating**
      * - `text` in database
      * - Nullable, no default
      */
      waterRating: string | null;
    }
    export interface Whereable {
      /**
      * **RopewikiPage.coordinates**
      * - `jsonb` in database
      * - Nullable, no default
      */
      coordinates?: db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.hike**
      * - `jsonb` in database
      * - Nullable, no default
      */
      hike?: db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.kmlUrl**
      * - `text` in database
      * - Nullable, no default
      */
      kmlUrl?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.maxTime**
      * - `jsonb` in database
      * - Nullable, no default
      */
      maxTime?: db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.minTime**
      * - `jsonb` in database
      * - Nullable, no default
      */
      minTime?: db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.months**
      * - `jsonb` in database
      * - Nullable, no default
      */
      months?: db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.pageId**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      pageId?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.permits**
      * - `text` in database
      * - Nullable, no default
      */
      permits?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.quality**
      * - `numeric` in database
      * - Nullable, no default
      */
      quality?: (number | db.NumericString) | db.Parameter<(number | db.NumericString)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (number | db.NumericString) | db.Parameter<(number | db.NumericString)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.rappelCount**
      * - `text` in database
      * - Nullable, no default
      */
      rappelCount?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.rappelLongest**
      * - `jsonb` in database
      * - Nullable, no default
      */
      rappelLongest?: db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.rating**
      * - `text` in database
      * - Nullable, no default
      */
      rating?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.region**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      region?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.riskRating**
      * - `text` in database
      * - Nullable, no default
      */
      riskRating?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.shuttle**
      * - `jsonb` in database
      * - Nullable, no default
      */
      shuttle?: db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.technicalRating**
      * - `text` in database
      * - Nullable, no default
      */
      technicalRating?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.timeRating**
      * - `text` in database
      * - Nullable, no default
      */
      timeRating?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.url**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      url?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.vehicle**
      * - `text` in database
      * - Nullable, no default
      */
      vehicle?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPage.waterRating**
      * - `text` in database
      * - Nullable, no default
      */
      waterRating?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **RopewikiPage.coordinates**
      * - `jsonb` in database
      * - Nullable, no default
      */
      coordinates?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.hike**
      * - `jsonb` in database
      * - Nullable, no default
      */
      hike?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.kmlUrl**
      * - `text` in database
      * - Nullable, no default
      */
      kmlUrl?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.maxTime**
      * - `jsonb` in database
      * - Nullable, no default
      */
      maxTime?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.minTime**
      * - `jsonb` in database
      * - Nullable, no default
      */
      minTime?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.months**
      * - `jsonb` in database
      * - Nullable, no default
      */
      months?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **RopewikiPage.pageId**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      pageId: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **RopewikiPage.permits**
      * - `text` in database
      * - Nullable, no default
      */
      permits?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.quality**
      * - `numeric` in database
      * - Nullable, no default
      */
      quality?: (number | db.NumericString) | db.Parameter<(number | db.NumericString)> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.rappelCount**
      * - `text` in database
      * - Nullable, no default
      */
      rappelCount?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.rappelLongest**
      * - `jsonb` in database
      * - Nullable, no default
      */
      rappelLongest?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.rating**
      * - `text` in database
      * - Nullable, no default
      */
      rating?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.region**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      region: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **RopewikiPage.riskRating**
      * - `text` in database
      * - Nullable, no default
      */
      riskRating?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.shuttle**
      * - `jsonb` in database
      * - Nullable, no default
      */
      shuttle?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.technicalRating**
      * - `text` in database
      * - Nullable, no default
      */
      technicalRating?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.timeRating**
      * - `text` in database
      * - Nullable, no default
      */
      timeRating?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.url**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      url: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **RopewikiPage.vehicle**
      * - `text` in database
      * - Nullable, no default
      */
      vehicle?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPage.waterRating**
      * - `text` in database
      * - Nullable, no default
      */
      waterRating?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **RopewikiPage.coordinates**
      * - `jsonb` in database
      * - Nullable, no default
      */
      coordinates?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.hike**
      * - `jsonb` in database
      * - Nullable, no default
      */
      hike?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.kmlUrl**
      * - `text` in database
      * - Nullable, no default
      */
      kmlUrl?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.maxTime**
      * - `jsonb` in database
      * - Nullable, no default
      */
      maxTime?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.minTime**
      * - `jsonb` in database
      * - Nullable, no default
      */
      minTime?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.months**
      * - `jsonb` in database
      * - Nullable, no default
      */
      months?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **RopewikiPage.pageId**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      pageId?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **RopewikiPage.permits**
      * - `text` in database
      * - Nullable, no default
      */
      permits?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.quality**
      * - `numeric` in database
      * - Nullable, no default
      */
      quality?: (number | db.NumericString) | db.Parameter<(number | db.NumericString)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (number | db.NumericString) | db.Parameter<(number | db.NumericString)> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.rappelCount**
      * - `text` in database
      * - Nullable, no default
      */
      rappelCount?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.rappelLongest**
      * - `jsonb` in database
      * - Nullable, no default
      */
      rappelLongest?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.rating**
      * - `text` in database
      * - Nullable, no default
      */
      rating?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.region**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      region?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **RopewikiPage.riskRating**
      * - `text` in database
      * - Nullable, no default
      */
      riskRating?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.shuttle**
      * - `jsonb` in database
      * - Nullable, no default
      */
      shuttle?: db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, db.JSONValue | db.Parameter<db.JSONValue> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.technicalRating**
      * - `text` in database
      * - Nullable, no default
      */
      technicalRating?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.timeRating**
      * - `text` in database
      * - Nullable, no default
      */
      timeRating?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.url**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      url?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **RopewikiPage.vehicle**
      * - `text` in database
      * - Nullable, no default
      */
      vehicle?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPage.waterRating**
      * - `text` in database
      * - Nullable, no default
      */
      waterRating?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'RopewikiPage_pkey' | 'uk_ropewikiPage_pageId';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **RopewikiPageBetaSection**
   * - Table in database
   */
  export namespace RopewikiPageBetaSection {
    export type Table = 'RopewikiPageBetaSection';
    export interface Selectable {
      /**
      * **RopewikiPageBetaSection.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt: Date;
      /**
      * **RopewikiPageBetaSection.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt: Date | null;
      /**
      * **RopewikiPageBetaSection.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      id: string;
      /**
      * **RopewikiPageBetaSection.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate: Date;
      /**
      * **RopewikiPageBetaSection.ropewikiPage**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      ropewikiPage: string;
      /**
      * **RopewikiPageBetaSection.text**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      text: string;
      /**
      * **RopewikiPageBetaSection.title**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      title: string;
      /**
      * **RopewikiPageBetaSection.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt: Date;
    }
    export interface JSONSelectable {
      /**
      * **RopewikiPageBetaSection.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt: db.TimestampString;
      /**
      * **RopewikiPageBetaSection.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt: db.TimestampString | null;
      /**
      * **RopewikiPageBetaSection.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      id: string;
      /**
      * **RopewikiPageBetaSection.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate: db.TimestampString;
      /**
      * **RopewikiPageBetaSection.ropewikiPage**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      ropewikiPage: string;
      /**
      * **RopewikiPageBetaSection.text**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      text: string;
      /**
      * **RopewikiPageBetaSection.title**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      title: string;
      /**
      * **RopewikiPageBetaSection.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt: db.TimestampString;
    }
    export interface Whereable {
      /**
      * **RopewikiPageBetaSection.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPageBetaSection.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPageBetaSection.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPageBetaSection.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPageBetaSection.ropewikiPage**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      ropewikiPage?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPageBetaSection.text**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      text?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPageBetaSection.title**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      title?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiPageBetaSection.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **RopewikiPageBetaSection.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPageBetaSection.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPageBetaSection.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPageBetaSection.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiPageBetaSection.ropewikiPage**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      ropewikiPage: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **RopewikiPageBetaSection.text**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      text: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **RopewikiPageBetaSection.title**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      title: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **RopewikiPageBetaSection.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **RopewikiPageBetaSection.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPageBetaSection.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPageBetaSection.id**
      * - `uuid` in database
      * - `NOT NULL`, default: `gen_random_uuid()`
      */
      id?: string | db.Parameter<string> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPageBetaSection.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiPageBetaSection.ropewikiPage**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      ropewikiPage?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **RopewikiPageBetaSection.text**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      text?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **RopewikiPageBetaSection.title**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      title?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **RopewikiPageBetaSection.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'RopewikiPageBetaSection_pkey' | 'uk_ropewikiPageBetaSection_ropewikiPage_title';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **RopewikiRegion**
   * - Table in database
   */
  export namespace RopewikiRegion {
    export type Table = 'RopewikiRegion';
    export interface Selectable {
      /**
      * **RopewikiRegion.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt: Date;
      /**
      * **RopewikiRegion.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt: Date | null;
      /**
      * **RopewikiRegion.id**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      id: string;
      /**
      * **RopewikiRegion.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate: Date;
      /**
      * **RopewikiRegion.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name: string;
      /**
      * **RopewikiRegion.parentRegion**
      * - `uuid` in database
      * - Nullable, no default
      */
      parentRegion: string | null;
      /**
      * **RopewikiRegion.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt: Date;
    }
    export interface JSONSelectable {
      /**
      * **RopewikiRegion.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt: db.TimestampString;
      /**
      * **RopewikiRegion.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt: db.TimestampString | null;
      /**
      * **RopewikiRegion.id**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      id: string;
      /**
      * **RopewikiRegion.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate: db.TimestampString;
      /**
      * **RopewikiRegion.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name: string;
      /**
      * **RopewikiRegion.parentRegion**
      * - `uuid` in database
      * - Nullable, no default
      */
      parentRegion: string | null;
      /**
      * **RopewikiRegion.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt: db.TimestampString;
    }
    export interface Whereable {
      /**
      * **RopewikiRegion.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiRegion.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiRegion.id**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      id?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiRegion.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiRegion.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiRegion.parentRegion**
      * - `uuid` in database
      * - Nullable, no default
      */
      parentRegion?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
      /**
      * **RopewikiRegion.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **RopewikiRegion.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiRegion.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiRegion.id**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      id: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **RopewikiRegion.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiRegion.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name: string | db.Parameter<string> | db.SQLFragment;
      /**
      * **RopewikiRegion.parentRegion**
      * - `uuid` in database
      * - Nullable, no default
      */
      parentRegion?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment;
      /**
      * **RopewikiRegion.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **RopewikiRegion.createdAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      createdAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiRegion.deletedAt**
      * - `timestamp` in database
      * - Nullable, no default
      */
      deletedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiRegion.id**
      * - `uuid` in database
      * - `NOT NULL`, no default
      */
      id?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **RopewikiRegion.latestRevisionDate**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      latestRevisionDate?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiRegion.name**
      * - `text` in database
      * - `NOT NULL`, no default
      */
      name?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
      /**
      * **RopewikiRegion.parentRegion**
      * - `uuid` in database
      * - Nullable, no default
      */
      parentRegion?: string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | null | db.DefaultType | db.SQLFragment>;
      /**
      * **RopewikiRegion.updatedAt**
      * - `timestamp` in database
      * - `NOT NULL`, default: `CURRENT_TIMESTAMP`
      */
      updatedAt?: (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment | db.SQLFragment<any, (db.TimestampString | Date) | db.Parameter<(db.TimestampString | Date)> | db.DefaultType | db.SQLFragment>;
    }
    export type UniqueIndex = 'RopewikiRegion_pkey' | 'uk_ropewikiRegion_name_parentRegion';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /**
   * **schema_migrations**
   * - Table in database
   */
  export namespace schema_migrations {
    export type Table = 'schema_migrations';
    export interface Selectable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      version: string;
    }
    export interface JSONSelectable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      version: string;
    }
    export interface Whereable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      version?: string | db.Parameter<string> | db.SQLFragment | db.ParentColumn | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment | db.ParentColumn>;
    }
    export interface Insertable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      version: string | db.Parameter<string> | db.SQLFragment;
    }
    export interface Updatable {
      /**
      * **schema_migrations.version**
      * - `varchar` in database
      * - `NOT NULL`, no default
      */
      version?: string | db.Parameter<string> | db.SQLFragment | db.SQLFragment<any, string | db.Parameter<string> | db.SQLFragment>;
    }
    export type UniqueIndex = 'schema_migrations_pkey';
    export type Column = keyof Selectable;
    export type OnlyCols<T extends readonly Column[]> = Pick<Selectable, T[number]>;
    export type SQLExpression = Table | db.ColumnNames<Updatable | (keyof Updatable)[]> | db.ColumnValues<Updatable> | Whereable | Column | db.ParentColumn | db.GenericSQLExpression;
    export type SQL = SQLExpression | SQLExpression[];
  }

  /* --- aggregate types --- */

  export namespace public {  
    export type Table = RopewikiImage.Table | RopewikiPage.Table | RopewikiPageBetaSection.Table | RopewikiRegion.Table | schema_migrations.Table;
    export type Selectable = RopewikiImage.Selectable | RopewikiPage.Selectable | RopewikiPageBetaSection.Selectable | RopewikiRegion.Selectable | schema_migrations.Selectable;
    export type JSONSelectable = RopewikiImage.JSONSelectable | RopewikiPage.JSONSelectable | RopewikiPageBetaSection.JSONSelectable | RopewikiRegion.JSONSelectable | schema_migrations.JSONSelectable;
    export type Whereable = RopewikiImage.Whereable | RopewikiPage.Whereable | RopewikiPageBetaSection.Whereable | RopewikiRegion.Whereable | schema_migrations.Whereable;
    export type Insertable = RopewikiImage.Insertable | RopewikiPage.Insertable | RopewikiPageBetaSection.Insertable | RopewikiRegion.Insertable | schema_migrations.Insertable;
    export type Updatable = RopewikiImage.Updatable | RopewikiPage.Updatable | RopewikiPageBetaSection.Updatable | RopewikiRegion.Updatable | schema_migrations.Updatable;
    export type UniqueIndex = RopewikiImage.UniqueIndex | RopewikiPage.UniqueIndex | RopewikiPageBetaSection.UniqueIndex | RopewikiRegion.UniqueIndex | schema_migrations.UniqueIndex;
    export type Column = RopewikiImage.Column | RopewikiPage.Column | RopewikiPageBetaSection.Column | RopewikiRegion.Column | schema_migrations.Column;
  
    export type AllBaseTables = [RopewikiImage.Table, RopewikiPage.Table, RopewikiPageBetaSection.Table, RopewikiRegion.Table, schema_migrations.Table];
    export type AllForeignTables = [];
    export type AllViews = [];
    export type AllMaterializedViews = [];
    export type AllTablesAndViews = [RopewikiImage.Table, RopewikiPage.Table, RopewikiPageBetaSection.Table, RopewikiRegion.Table, schema_migrations.Table];
  }



  /* === global aggregate types === */

  export type Schema = 'public';
  export type Table = public.Table;
  export type Selectable = public.Selectable;
  export type JSONSelectable = public.JSONSelectable;
  export type Whereable = public.Whereable;
  export type Insertable = public.Insertable;
  export type Updatable = public.Updatable;
  export type UniqueIndex = public.UniqueIndex;
  export type Column = public.Column;

  export type AllSchemas = ['public'];
  export type AllBaseTables = [...public.AllBaseTables];
  export type AllForeignTables = [...public.AllForeignTables];
  export type AllViews = [...public.AllViews];
  export type AllMaterializedViews = [...public.AllMaterializedViews];
  export type AllTablesAndViews = [...public.AllTablesAndViews];


  /* === lookups === */

  export type SelectableForTable<T extends Table> = {
    "RopewikiImage": RopewikiImage.Selectable;
    "RopewikiPage": RopewikiPage.Selectable;
    "RopewikiPageBetaSection": RopewikiPageBetaSection.Selectable;
    "RopewikiRegion": RopewikiRegion.Selectable;
    "schema_migrations": schema_migrations.Selectable;
  }[T];

  export type JSONSelectableForTable<T extends Table> = {
    "RopewikiImage": RopewikiImage.JSONSelectable;
    "RopewikiPage": RopewikiPage.JSONSelectable;
    "RopewikiPageBetaSection": RopewikiPageBetaSection.JSONSelectable;
    "RopewikiRegion": RopewikiRegion.JSONSelectable;
    "schema_migrations": schema_migrations.JSONSelectable;
  }[T];

  export type WhereableForTable<T extends Table> = {
    "RopewikiImage": RopewikiImage.Whereable;
    "RopewikiPage": RopewikiPage.Whereable;
    "RopewikiPageBetaSection": RopewikiPageBetaSection.Whereable;
    "RopewikiRegion": RopewikiRegion.Whereable;
    "schema_migrations": schema_migrations.Whereable;
  }[T];

  export type InsertableForTable<T extends Table> = {
    "RopewikiImage": RopewikiImage.Insertable;
    "RopewikiPage": RopewikiPage.Insertable;
    "RopewikiPageBetaSection": RopewikiPageBetaSection.Insertable;
    "RopewikiRegion": RopewikiRegion.Insertable;
    "schema_migrations": schema_migrations.Insertable;
  }[T];

  export type UpdatableForTable<T extends Table> = {
    "RopewikiImage": RopewikiImage.Updatable;
    "RopewikiPage": RopewikiPage.Updatable;
    "RopewikiPageBetaSection": RopewikiPageBetaSection.Updatable;
    "RopewikiRegion": RopewikiRegion.Updatable;
    "schema_migrations": schema_migrations.Updatable;
  }[T];

  export type UniqueIndexForTable<T extends Table> = {
    "RopewikiImage": RopewikiImage.UniqueIndex;
    "RopewikiPage": RopewikiPage.UniqueIndex;
    "RopewikiPageBetaSection": RopewikiPageBetaSection.UniqueIndex;
    "RopewikiRegion": RopewikiRegion.UniqueIndex;
    "schema_migrations": schema_migrations.UniqueIndex;
  }[T];

  export type ColumnForTable<T extends Table> = {
    "RopewikiImage": RopewikiImage.Column;
    "RopewikiPage": RopewikiPage.Column;
    "RopewikiPageBetaSection": RopewikiPageBetaSection.Column;
    "RopewikiRegion": RopewikiRegion.Column;
    "schema_migrations": schema_migrations.Column;
  }[T];

  export type SQLForTable<T extends Table> = {
    "RopewikiImage": RopewikiImage.SQL;
    "RopewikiPage": RopewikiPage.SQL;
    "RopewikiPageBetaSection": RopewikiPageBetaSection.SQL;
    "RopewikiRegion": RopewikiRegion.SQL;
    "schema_migrations": schema_migrations.SQL;
  }[T];

}
